### ISSUE TITLE
rudo

### ISSUE THREAD

**Issue by asceth** [jasondew/ors#9]
Do you want me to go ahead and create the rudo repository and switch the ors bin command?

**Comment by jasondew** [comment]
honestly the more i think about it, the less enthused i am about the name.. want to marinate on it more or do you still like it? 

## 

Jason Dew
jason.dew@gmail.com

**Comment by asceth** [comment]
I honestly like effin more.  :)  We can marinate on it some more though since it isn't a critical change.

**Comment by jasondew** [comment]
What about just `fin` ? 

## 

Jason Dew
jason.dew@gmail.com

**Comment by asceth** [comment]
Are you just wanting to shorten it?  I like `effin` for the tagline "because sometimes you just want to `effin deploy`" while I can't think of a good line for `fin`.

**Comment by jasondew** [comment]
Pretty much, yea. I was thinking the same mnemonic -- "just f-in deploy" 

## 

Jason Dew
jason.dew@gmail.com

**Comment by asceth** [comment]
hehe that makes sense to me.  I can see the conversations now "Hey I pushed some changes up, can you go ahead and f'in deploy?"  :)

**Comment by jasondew** [comment]
well. that's not going to work either :(  http://rubygems.org/gems/fin

**Comment by asceth** [comment]
`dor` similar to the rudo  "do ruby" or "do rails" when "expanded".

"do rails deploy to production" -> `dor deploy to production`

btw rudo is taken as well.

**Comment by jasondew** [comment]
Bah. I wonder if it's worth it at this point. I'm fine with leaving the name as is -- objections?

**Comment by asceth** [comment]
fine by me.
